version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.local-db
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    networks:
      - quarkus-net
    ports:
      - "5432:5432"

networks:
  quarkus-net:
    driver: bridge
